### ISSUE TITLE
Check template fe_page in insertJavascriptIntoFullPage

### ISSUE THREAD

**Issue by rabauss** [systemhaus/contao-cookiebot#4]
Can we restrict the method `insertJavascriptIntoFullPage` to templates that start with `fe_page`?
This would improve the performance, since not every hook call would load the root page and attempt to do a string replacement.

Just wanted to leave this here for discussion.

**Comment by ghost** [comment]
Well, it would at least have to be `fe_*`, because you can choose any name for your template.
