### ISSUE TITLE
Contao 4.9.2

### ISSUE THREAD

**Issue by jrson83** [systemhaus/contao-cookiebot#8]
Is the module compatible with Contao 4.9.2? I installed with composer and updated the database. In Contao Manager I can see the package is installed, but I can't find API Settings in the backend.
Where do I need to modify the API Settings in the backend?

**Comment by tsarma** [comment]
Same issue with Contao 4.9.4

**Comment by plorenz-etes** [comment]
Sorry for the late reply - this is now fixed in version 1.3.0.
