### ISSUE TITLE
Composer update is not working in Contao 4.4

### ISSUE THREAD

**Issue by netzarbeiter** [systemhaus/contao-cookiebot#9]
With the following [commit](https://github.com/systemhaus/contao-cookiebot/commit/4df22704d916624ec4a36a07fb97ace3c5a64560
) you added the page rootfallback for Contao 4.9, updating a system with Contao 4.4 is now not longer working.

Error message:
`[console] Error thrown while running command "cache:warmup --env=prod". Message: "Palette "rootfallback" not found in table "tl_page"" ["exception" => Contao\CoreBundle\Exception\PaletteNotFoundException { …},"command" => "cache:warmup --env=prod","message" => "Palette "rootfallback" not found in table "tl_page""]`

**Comment by plorenz-etes** [comment]
Thank you for bringing this to our attention.
We have released version 1.3.1 which fixes this issue.
